name: reports_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  vertical_tabs: ^0.1.4

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Our dependencies
  flutter_web_browser: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    # Jsons
    - assets/content/home.json
    - assets/content/topics.json
    - assets/content/reports.json

    # Home images
    - assets/images/home/2T2000s_icon.PNG
    - assets/images/home/2T2000s-playstore.jpeg
    - assets/images/home/2T2000s.png
    - assets/images/home/2T2000s2.png
    - assets/images/home/animation1.gif
    - assets/images/home/fotoNico.jpg
    - assets/images/home/fotoRogelio.png
    - assets/images/home/SpaceX_1.jpg
    - assets/images/home/SpaceX_2.jpg
    - assets/images/home/SpaceX_icon.png
    - assets/images/home/spacex-playstore.jpeg
    - assets/images/home/version1.jpg

    # Performance images
    - assets/images/performance/noLoadedFilters.gif
    - assets/images/performance/noLoadedFilters(1).gif
    - assets/images/performance/loadedFilters.gif
    - assets/images/performance/loadedFilters(1).gif
    - assets/images/performance/battery_usage_2T2000S.jpg    
    - assets/images/performance/battery_usage_spacex.jpg  
    - assets/images/performance/memory_usage_initial.jpg  
    - assets/images/performance/cpu_usage_initial.jpg 
    - assets/images/performance/memory_usage_spacex.jpg  
    - assets/images/performance/cpu_usage_spacex.jpg 
    - assets/images/performance/memory_usage_2T2000S.jpg  
    - assets/images/performance/cpu_usage_2T2000S.jpg 
    - assets/images/performance/lint_2_2T2000S.jpg
    - assets/images/performance/lint_3_2T2000S.png
    - assets/images/performance/lint_2T2000S.jpg
    - assets/images/performance/multithreading_2T2000S.jpg
    - assets/images/performance/results.jpg
    - assets/images/performance/lint_1_spacex.png

    # Storage images
    - assets/images/storage/storage_1_2T2000S.png
    - assets/images/storage/storage_2_2T2000S.png
    - assets/images/storage/storage_3_2T2000S.png
    - assets/images/storage/storage_4_spacex.PNG
    - assets/images/storage/storage_5_spacex.PNG
    - assets/images/storage/storage_6_spacex.PNG
    - assets/images/storage/storage_7_spacex.PNG
    - assets/images/storage/storage_8_spacex.gif
    - assets/images/storage/storage_9_spacex.PNG
    - assets/images/storage/storage_10_spacex.PNG
    - assets/images/storage/storage_11_spacex.jpeg
    - assets/images/storage/storage_12_spacex.PNG
    - assets/images/storage/storage_13_spacex.PNG

    # Rendering images
    - assets/images/rendering/ui1.jpeg
    - assets/images/rendering/ui2.jpeg
    - assets/images/rendering/ui3.jpeg
    - assets/images/rendering/animation1.gif
    - assets/images/rendering/animation2.gif
    - assets/images/rendering/animation31.gif
    - assets/images/rendering/rendering11.gif
    - assets/images/rendering/scrollbloc.png
    - assets/images/rendering/info1.jpeg
    - assets/images/rendering/apppage.png
    - assets/images/rendering/fadetransition.png
    - assets/images/rendering/camera1.jpeg

    # Code images

    - assets/images/code/code_1_2T2000S.png
    - assets/images/code/code_2_2T2000S.png
    - assets/images/code/code_3_2T2000S.png
    - assets/images/code/code_4_2T2000S.png
    - assets/images/code/code_5_2T2000S.png
    - assets/images/code/code_6_2T2000S.png
    - assets/images/code/code_7_2T2000S.png
    - assets/images/code/code_8_2T2000S.png
    - assets/images/code/code_9_2T2000S.png
    - assets/images/code/code_10_2T2000S.png
    - assets/images/code/code_11_2T2000S.png
    - assets/images/code/code_12_2T2000S.png
    - assets/images/code/code_1_spacex.png
    - assets/images/code/code_2_spacex.png
    - assets/images/code/code_3_spacex.png
    - assets/images/code/code_4_spacex.png
    - assets/images/code/code_5_spacex.png
    - assets/images/code/code_6_spacex.png
    - assets/images/code/code_7_spacex.png

    # Connectivity images

    # Other images

    - assets/images/other/loading.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
